log_levels:
  agent: 0
  camp: 0
  init: 0
  flood: 0
  link: 0

# Set to 100 to scale down the population by 100 and increase the execution time.
optimisations:
  hasten: 10
  PopulationScaleDownFactor: 1

spawn_rules:
  conflict_zone_spawning_only: False
  take_from_population: True
  hurricane_driven_spawning:
    flood_spawn_mode: "pop_ratio"
    displaced_per_flood_day: [0.0,0.1,0.3,0.5,0.7]
    HurricaneLevelInputFile: "hurricane_zones.csv"
  hurricane_impact_map:
    1: 0.3 # Tropical depression 
    2: 0.4 # Tropical storm
    3: 0.6 # Category 1 hurricane
    4: 0.9 # Category 2-3 hurricane
    5: 1.0 # Category 4-5 hurricane

  evacuation_threshold: 2
  
move_rules:
  default_movechance: 0.6
  awareness_level: 1
  start_on_foot: True


